import time
from time import gmtime, strftime
import datetime

from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
import selenium.webdriver.support.ui as ui
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.opera.options import Options
from selenium.webdriver.safari.permissions import Permission
options = Options()
options.add_argument('--user-data-dir=/Users/marc.jackson/Desktop/SeleniumLogOn')
options.add_argument("start-maximized")
options.add_argument("disable-infobars")
options.add_experimental_option("prefs", {
    "profile.default_content_setting_values.media_stream_mic": 1,
    "profile.default_content_setting_values.media_stream_camera": 1,
    "profile.default_content_setting_values.geolocation": 1,
    "profile.default_content_setting_values.notifications": 1})
from selenium import webdriver
driver = webdriver.Chrome('/Users/marc.jackson/PycharmProjects/untitled/venv/Selenium/Remote/chromedriver')
a = ActionChains(driver)
testurl = 'https://dave.uktv.co.uk/'
driver.get(testurl)
driver.implicitly_wait(1)
HomeIconFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[1]/a')
TVGuideFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[2]/a')
print(TVGuideFT.get_attribute('href'))
OnDemandFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[3]/a')
print(OnDemandFT.get_attribute('href'))
ShowsFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[4]/a')
print(ShowsFT.get_attribute('href'))
ArticlesFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[5]/a')
print(ArticlesFT.get_attribute('href'))
HighlightsFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[6]/a')
print(HighlightsFT.get_attribute('href'))
WatchLiveFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[7]/a')
print(WatchLiveFT.get_attribute('href'))
# Footer (Mid)
PrivacyPolicy = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[1]/a')
print(PrivacyPolicy.get_attribute('href'))
TandC = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[2]/a')
print(TandC.get_attribute('href'))
CookieFooter = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[3]/a')
print(CookieFooter.get_attribute('href'))
Slavery = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[4]/a')
print(Slavery.get_attribute('href'))
ContactUs = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[5]/a')
print(ContactUs.get_attribute('href'))
Help = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[6]/a')
print(Help.get_attribute('href'))
Corp = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[7]/a')
print(Corp.get_attribute('href'))
PG = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[8]/a')
print(PG.get_attribute('href'))
HowTo = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[9]/a')
print(HowTo.get_attribute('href'))
# Footer (Bottom)
UKTVCorpLogo = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/h4/a')
print(UKTVCorpLogo.get_attribute('href'))
WChannel = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[1]/li[1]/a')
print(WChannel.get_attribute('href'))
Dave = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[1]/li[2]/a')
print(Dave.get_attribute('href'))
Alibi = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[1]/li[3]/a')
print(Alibi.get_attribute('href'))
Gold = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[1]/li[4]/a')
print(Gold.get_attribute('href'))
Eden = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[2]/li[1]/a')
print(Eden.get_attribute('href'))
Drama = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[2]/li[2]/a')
print(Drama.get_attribute('href'))
Yesterday = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[2]/li[3]/a')
print(Yesterday.get_attribute('href'))
UKTVPlay = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[2]/li[4]/a')
print(UKTVPlay.get_attribute('href'))
# Social Media Links
facebookfooter = driver.find_element_by_xpath('//*[@id="site-footer"]/section/div/ul/li[1]/a')
print(facebookfooter.get_attribute('href'))
twitterfooter = driver.find_element_by_xpath('//*[@id="site-footer"]/section/div/ul/li[2]/a')
print(twitterfooter.get_attribute('href'))
youtubefooter = driver.find_element_by_xpath('//*[@id="site-footer"]/section/div/ul/li[3]/a')
print(youtubefooter.get_attribute('href'))
newsletterfooter = driver.find_element_by_xpath('//*[@id="site-footer"]/section/div/ul/li[4]/a')
print(facebookfooter.get_attribute('href'))
HeroImageArrowRightElemet = driver.find_element_by_xpath('//*[@id="dave-hero-slider"]/ul/li[2]/a')
HeroImageArrowRightElemet.click()
driver.implicitly_wait(1)
HeroImageArrowLeftElement = driver.find_element_by_xpath('//*[@id="dave-hero-slider"]/ul/li[1]/a')
HeroImageArrowLeftElement.click()
#LatestTabElement = driver.find_element_by_xpath('//*[@id="catchup-widget-tabs"]/li[2]/a')
#LatestTabElement.click()
#ATOZMainPageElement = driver.find_element_by_xpath('/html/body/div/div[4]/div[2]/main/div[2]/div[2]/div/div/ul/li[3]/a')
#ATOZMainPageElement.click()
driver.execute_script("window.open('about:blank', 'tab2');")
driver.switch_to.window("tab2")
driver.get('http://uktvplay.uktv.co.uk/channel/dave/')
time.sleep(3)
CookieNotice = driver.find_element_by_xpath('//*[@id="app"]/div[1]/div/h2')
CookiePolicy = driver.find_element_by_xpath('//*[@id="app"]/div[1]/div/div/a').get_attribute('href')
print(CookiePolicy)
CookieYes = driver.find_element_by_xpath('//*[@id="app"]/div[1]/div/div/button').click()
time.sleep(2)
driver.execute_script("window.open('about:blank', 'tab3');")
driver.switch_to.window("tab3")
driver.get('https://dave.uktv.co.uk/shows/')
time.sleep(2)
driver.execute_script("window.open('about:blank', 'tab4');")
driver.switch_to.window("tab4")
driver.get('https://dave.uktv.co.uk/tv-guide/')
time.sleep(2)
driver.execute_script("window.open('about:blank', 'tab5');")
driver.switch_to.window("tab5")
driver.get('https://dave.uktv.co.uk/podcasts/')
time.sleep(2)
driver.execute_script("window.open('about:blank', 'tab6');")
driver.switch_to.window("tab6")
driver.get('https://dave.uktv.co.uk/competitions/')
time.sleep(2)
driver.execute_script("window.open('about:blank', 'tab7');")
driver.switch_to.window("tab7")
driver.get('https://dave.uktv.co.uk/motoring/')
time.sleep(2)
driver.execute_script("window.open('about:blank', 'tab8');")
driver.switch_to.window("tab8")
driver.get('https://uktvplay.uktv.co.uk/watch-live/dave')
time.sleep(2)

EpisodesOnTV = driver.find_element_by_xpath('//*[@id="main-content"]/div/div[2]/section/div/div[2]/button')
EpisodesOnTV.click()
RightArrowClickElement = driver.find_element_by_xpath('//*[@id="main-content"]/div/section/div/div/div/div/button[2]')
RightArrowClickElement.click()
driver.implicitly_wait(1)
LeftArrowClickElement = driver.find_element_by_xpath('//*[@id="main-content"]/div/section/div/div/div/div/button[1]')
LeftArrowClickElement.click()
driver.close()
driver.switch_to.window("tab7")

driver.implicitly_wait(1)
FirstThumbnailElement = driver.find_element_by_xpath('//*[@id="main-content"]/div[1]/div/div/div/div[1]/a')
FirstThumbnailElement.click()
driver.implicitly_wait(1)
#ShowMoreButtonElement= driver.find_element_by_xpath('//*[@id="main-content"]/div[1]/div/nav/a')
#ShowMoreButtonElement.click()
#RemindMeButtonElement = driver.find_element_by_xpath('//*[@id="notify-btn"]')
#RemindMeButtonElement.click()
ClickPlayIconElement = driver.find_element_by_xpath('//*[@id="main-content"]/figure/a/i')
ClickPlayIconElement.click()

driver.close()
driver.switch_to.window("tab6")
driver.implicitly_wait(1)
driver.close()
driver.switch_to.window("tab5")
driver.implicitly_wait(1)

FirstPodcastThumbnailElement = driver.find_element_by_xpath('//*[@id="main-content"]/div[1]/div/div/div[1]/div[1]/a/img')
FirstPodcastThumbnailElement.click()
driver.implicitly_wait(1)
driver.close()
driver.switch_to.window("tab4")


#TV GUIDE TAB ELEMENTS
#EveningToggleElement = driver.find_element_by_css_selector('#jump-to-primetime')
#EveningToggleElement.click()

#driver.implicitly_wait(1)
#TVGuidBackArrowElement = driver.find_element_by_xpath('//*[@id="tv-listings-page"]/nav/a[1]/i')
#TVGuidBackArrowElement.click()
#driver.implicitly_wait(1)
#TVGuideForwardArrowElement = driver.find_element_by_xpath('//*[@id="tv-listings-page"]/nav/a[2]/i')
#TVGuideForwardArrowElement.click()

driver.close()
driver.switch_to.window("tab3")
driver.implicitly_wait(1)
#Show Tab Elements
#AtoZTab = driver.find_element_by_css_selector('#main-content > div.programmes-container.widget.widget-bg > ul > li.az > a')
#AtoZTab.click()
#A2ZLetterA = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[2]/a')
#A2ZLetterA.click()
#A2ZLetterB = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[3]/a')
#A2ZLetterB.click()
#A2ZLetterC = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[4]/a')
#A2ZLetterC.click()
#A2ZLetterD = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[5]/a')
#A2ZLetterD.click()
#A2ZLetterE = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[6]/a')
#A2ZLetterE.click()
#A2ZLetterF = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[7]/a')
#A2ZLetterF.click()
#A2ZLetterG = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[8]/a')
#A2ZLetterG.click()
#A2ZLetterH = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[9]/a')
#A2ZLetterH.click()

driver.close()
driver.switch_to.window("tab2")
driver.close()


#Don't User Until Fixed.
#A2ZLetterI = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[10]/a')
#A2ZLetterJ = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[11]/a')
#A2ZLetterK = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[12]')
#A2ZLetterL = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[13]/a')
#A2ZLetterM = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[14]/a')
#A2ZLetterN = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[15]/a')
#A2ZLetterO = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[16]/a')
#A2ZLetterP = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[17]')
#A2ZLetterQ = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[18]/a')
#A2ZLetterR = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[19]/a')
#A2ZLetterS = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[20]/a')
#A2ZLetterT = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[21]/a')
#A2ZLetterU = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[22]/a')
#A2ZLetterV = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[23]')
#A2ZLetterW = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[24]/a')
#A2ZLetterX = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[25]')
#A2ZLetterY = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[26]/a')
#A2ZLetterZ = driver.find_element_by_xpath('//*[@id="vod-atoz"]/nav/ol/li[27]/a')



#MostPopularTab.click()
#time.sleep(1)
#LatestTab.click()
##time.sleep(1)
#AtoZTab.click()

#Show Tab Elements
#STAtoZtab = driver.find_element_by_css_selector('#main-content > div.programmes-container.widget.widget-bg > ul > li.az.active')
#STAtoZtabLetterA = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[2]/a')
#STAtoZtabLetterB = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[3]/a')
#STAtoZtabLetterC = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[4]/a')
#STAtoZtabLetterD = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[5]/a')
#STAtoZtabLetterE = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[6]/a')
#STAtoZtabLetterF = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[7]/a')
#STAtoZtabLetterG = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[8]/a')
#STAtoZtabLetterH = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[9]/a')
#STAtoZtabLetterI = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[10]/a')
#STAtoZtabLetterJ = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[11]/a')
#STAtoZtabLetterK = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[12]/a')
#STAtoZtabLetterL = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[13]/a')
#STAtoZtabLetterM = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[14]/a')
#STAtoZtabLetterN = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[15]/a')
#STAtoZtabLetterO = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[16]/a')
#STAtoZtabLetterP = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[17]/a')
#STAtoZtabLetterQ = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[18]/a')
#STAtoZtabLetterR = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[19]/a')
#STAtoZtabLetterS = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[20]/a')
#STAtoZtabLetterT = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[21]/a')
#STAtoZtabLetterU = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[22]/a')
#STAtoZtabLetterV = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[23]/a')
#STAtoZtabLetterW = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[24]/a')
#STAtoZtabLetterX = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[25]/a')
#STAtoZtabLetterY = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[26]/a')
#STAtoZtabLetterZ = driver.find_element_by_xpath('//*[@id="shows-az"]/nav/ol/li[27]/a')
#TVGuideCTA = driver.find_element_by_xpath('//*[@id="sidebar"]/aside/div/div[2]/a')
#STshowmorebutton= driver.find_element_by_xpath('//*[@id="sidebar"]/div[3]/div/nav/a')
#TwitterModalS = driver.find_element_by_xpath('//*[@id="u_0_1"]/div[1]')

#driver.implicitly_wait(10)
#STAtoZtab.click()

