# -- Footers --
# Footer (Top)
HomeIconFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[1]/a')
TVGuideFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[2]/a')
print(TVGuideFT.get_attribute('href'))
OnDemandFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[3]/a')
print(OnDemandFT.get_attribute('href'))
ShowsFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[4]/a')
print(ShowsFT.get_attribute('href'))
ArticlesFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[5]/a')
print(ArticlesFT.get_attribute('href'))
HighlightsFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[6]/a')
print(HighlightsFT.get_attribute('href'))
WatchLiveFT = driver.find_element_by_xpath('//*[@id="footer-nav"]/li[7]/a')
print(WatchLiveFT.get_attribute('href'))
# Footer (Mid)
PrivacyPolicy = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[1]/a')
print(PrivacyPolicy.get_attribute('href'))
TandC = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[2]/a')
print(TandC.get_attribute('href'))
CookieFooter = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[3]/a')
print(CookieFooter.get_attribute('href'))
Slavery = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[4]/a')
print(Slavery.get_attribute('href'))
ContactUs = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[5]/a')
print(ContactUs.get_attribute('href'))
Help = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[6]/a')
print(Help.get_attribute('href'))
Corp = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[7]/a')
print(Corp.get_attribute('href'))
PG = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[8]/a')
print(PG.get_attribute('href'))
HowTo = driver.find_element_by_xpath('//*[@id="static-footer"]/div[2]/nav/ul/li[9]/a')
print(HowTo.get_attribute('href'))
# Footer (Bottom)
UKTVCorpLogo = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/h4/a')
print(UKTVCorpLogo.get_attribute('href'))
WChannel = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[1]/li[1]/a')
print(WChannel.get_attribute('href'))
Dave = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[1]/li[2]/a')
print(Dave.get_attribute('href'))
Alibi = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[1]/li[3]/a')
print(Alibi.get_attribute('href'))
Gold = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[1]/li[4]/a')
print(Gold.get_attribute('href'))
Eden = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[2]/li[1]/a')
print(Eden.get_attribute('href'))
Drama = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[2]/li[2]/a')
print(Drama.get_attribute('href'))
Yesterday = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[2]/li[3]/a')
print(Yesterday.get_attribute('href'))
UKTVPlay = driver.find_element_by_xpath('//*[@id="footer-site-links"]/nav/ul[2]/li[4]/a')
print(UKTVPlay.get_attribute('href'))
# Social Media Links
facebookfooter = driver.find_element_by_xpath('//*[@id="site-footer"]/section/div/ul/li[1]/a')
print(facebookfooter.get_attribute('href'))
twitterfooter = driver.find_element_by_xpath('//*[@id="site-footer"]/section/div/ul/li[2]/a')
print(twitterfooter.get_attribute('href'))
youtubefooter = driver.find_element_by_xpath('//*[@id="site-footer"]/section/div/ul/li[3]/a')
print(youtubefooter.get_attribute('href'))
newsletterfooter = driver.find_element_by_xpath('//*[@id="site-footer"]/section/div/ul/li[4]/a')
print(facebookfooter.get_attribute('href'))
ScrollPage.send_keys(Keys.HOME)
print('Footer Passed')










